---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  user1:
    displayname: "User1"
    # Password is Authelia
    password: "$argon2id$v=19$m=65536,t=1,p=8$bjRlVlg4T3QvdVNNT2hYSg$9gS10lSiFxdCdqZT0fKIdJofSsjpQmbLcIdyxpxwtJ0" 
    email: user1@email.com
    groups:
      - admins
      - dev

#To hash password run: docker run authelia/authelia:latest authelia hash-password yourpassword
...
